use_frameworks!

platform :ios, '8.0'

target 'PrivateHelloWorld_Example' do
  pod 'PrivateHelloWorld', :path => '../'

  target 'PrivateHelloWorld_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
